repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      - id: ruff-check
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black --check
        language: system
        types: [python]
      - id: isort
        name: isort
        entry: isort --check-only
        language: system
        types: [python]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic==2.11.9
          - sqlalchemy==2.0.43
