"""Complete ORM model registry for Alembic metadata discovery."""

from app.models.account import (
    OnboardingAnswer,
    OnboardingQuestion,
    OnboardingQuestionSet,
    OnboardingSession,
    RefreshToken,
    User,
    UserPreference,
)
from app.models.base import Base
from app.models.experience import (
    ChatConversation,
    ChatMessage,
    HotelRecommendation,
    RecommendationRun,
    Trip,
    TripAttributePreference,
)
from app.models.geography import City, Country, Locality, Region
from app.models.hotel import (
    Amenity,
    DataSource,
    Hotel,
    HotelAmenity,
    HotelImage,
    HotelSourceMapping,
    Review,
    ReviewImage,
)
from app.models.operations import (
    AuditLog,
    DataQualityIssue,
    HotelReviewFetchStatus,
    ImportJob,
    ScrapeCheckpoint,
    ScrapeFailure,
    ScrapeRun,
    SystemSetting,
)
from app.models.scoring import (
    AlgorithmVersion,
    Attribute,
    AttributeAlias,
    AttributeCategory,
    HotelAttributeScore,
    NormalizationRun,
    ReviewAttributeMention,
    ReviewProcessingStatus,
)

__all__ = [
    "AlgorithmVersion",
    "Amenity",
    "Attribute",
    "AttributeAlias",
    "AttributeCategory",
    "AuditLog",
    "Base",
    "ChatConversation",
    "ChatMessage",
    "City",
    "Country",
    "DataQualityIssue",
    "DataSource",
    "Hotel",
    "HotelAmenity",
    "HotelAttributeScore",
    "HotelImage",
    "HotelRecommendation",
    "HotelReviewFetchStatus",
    "HotelSourceMapping",
    "ImportJob",
    "Locality",
    "NormalizationRun",
    "OnboardingAnswer",
    "OnboardingQuestion",
    "OnboardingQuestionSet",
    "OnboardingSession",
    "RecommendationRun",
    "RefreshToken",
    "Region",
    "Review",
    "ReviewAttributeMention",
    "ReviewProcessingStatus",
    "ReviewImage",
    "ScrapeCheckpoint",
    "ScrapeFailure",
    "ScrapeRun",
    "SystemSetting",
    "Trip",
    "TripAttributePreference",
    "User",
    "UserPreference",
]
